
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



### Background

The goal of this tutorial is to introduce principles of Geostatical data analysis in R. Geostatistics is a branch of statistical sciences that studies spatial/temporal phenomena & capitalizes on spatial relationships to model possible values of variable(s) at unobserved, unsampled locations (Caers, 2005). Geostatistical tools are useful for interpolation of sampled data and simulation/prediction of phenomena. 

Generally, geostatistics deals with the analysis of **random fields** $Z(s)$, where *Z* is a random variable and *s* the non-random spatial index. Basically, at a limited number of sampled locations, measurements on *Z* are available,
and prediction (interpolation) of *Z* is required at non-observed locations
$s_0$, or the mean of *Z* is required over a specific region $B_0$. Geostatistical analysis involves estimation and modelling of spatial correlation (covariance or semivariance), and evaluating whether simplifying assumptions such as stationarity can be justified or need refinement. Advanced topics include the conditional simulation of Z(s), for example over locations on a grid, and model-based inference, which propagates uncertainty of correlation parameters through spatial predictions or simulations.

We will use **gstat** package, because it offers the widest geostatistical functionality in R namely: 

1. variogram cloud diagnostics, 
2. variogram modelling, 
3. simple kriging to local universal cokriging, 
4. multivariate geostatistics, 
5. block kriging, 
6. indicator kriging and, 
7. Gaussian conditional simulation e.t.c

### Structure

The tutorial is organized into exercises as follows:

1. Exercise 1: [Manipulating data in R Exercise](ex1_intro2R.html).
2. [Solutions to Exercise 1](ex1_intro2R_answers.html).
3. Exercise 2:

### Resources

We will use R software. R software is opensource and can be downloaded from https://cran.r-project.org/. A suitable R user interface that we shall use is [R Studio](https://rstudio.com/products/rstudio/download/). First download and install the latest version of R followed by the editor (RStudio). Other editors are available and you are free to use depending on your preference or previous experience.

### References

Caers, J. (2005). [*Petroleum geostatistics*](https://store.spe.org/Petroleum-Geostatistics-P45.aspx). Society of Petroleum Engineers Richardson