---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Spatial interpolation (prediction)

Spatial interpolation/prediction is necessary in various application because it helps:

  a. Predict a variable across space, including in areas where there are little to no data.
  b. To smooth the data across space so that we cannot interpret the results of individuals, but still, identify the general trends from the data. This is particularly useful when the data corresponds to individual persons and disclosing their locations is unethical.
  
For instance, due to economic and time constraints measurements may be sampled and later prediction done at unobserved locations using spatial interpolation models. Spatial prediction models (algorithms) can be grouped according to the amount of statistical analysis i.e. amount of expert knowledge included in the analysis. The following are the main groupings of interpolation techniques:

### Deterministic (non-geostatistical) interpolation/prediction models 

These are models where arbitrary or empirical model parameters are used. No estimate of the model error is available and usually no strict assumptions about the variability of a feature exist. The most common techniques that belong to this group are:

  a. Inverse distance weighted interpolation;
  b. Thiessen polygons;
  c. Natural neighbour interpolation;
  d. Polynomial trend surfaces;
  e. Splines;
  f. Radial Basis Function Interpolation

### Geostatistical interpolation techniques.

in this case, the model parameters are commonly estimated in an objective way, following probability theory. The predictions are accompanied with an estimate of the prediction error. A drawback is that the input data set usually need to satisfy strict statistical assumptions. There are at least four groups of linear statistical models:

  a. kriging (plain geostatistics);
  b. environmental correlation (e.g. regression-based);
  c. Bayesian-based models (e.g. Bayesian Maximum Entropy);
  d. hybrid models (e.g. regression-kriging).
  
In the next lesson we cover the first category (non-geostatistical).

## References

De Smith, M. J., Goodchild, M. F., & Longley, P. (2018). [*Geospatial analysis: a comprehensive guide to principles, techniques and software tools*](https://www.spatialanalysisonline.com/HTML/index.html). Troubador publishing ltd.

